/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pro.analyticslab.bot;

import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder;
import net.dv8tion.jda.api.sharding.ShardManager;
import net.dv8tion.jda.api.utils.MemberCachePolicy;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

public class App {
    public ShardManager shardManager;

    public App() {
        DefaultShardManagerBuilder builder = DefaultShardManagerBuilder.createDefault(
                Props.getProperty("analyticslab.discord.auth"),
                GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_PRESENCES, GatewayIntent.MESSAGE_CONTENT,
                GatewayIntent.GUILD_EMOJIS_AND_STICKERS, GatewayIntent.GUILD_MESSAGES, GatewayIntent.GUILD_VOICE_STATES,
                GatewayIntent.GUILD_INVITES, GatewayIntent.GUILD_WEBHOOKS, GatewayIntent.SCHEDULED_EVENTS
        )
                .setMemberCachePolicy(MemberCachePolicy.NONE)
                .enableCache(
                        CacheFlag.MEMBER_OVERRIDES,
                        CacheFlag.EMOJI,
                        CacheFlag.STICKER,
                        CacheFlag.VOICE_STATE
                )
                .disableCache(
                        CacheFlag.ACTIVITY,
                        CacheFlag.CLIENT_STATUS,
                        CacheFlag.FORUM_TAGS,
                        CacheFlag.ONLINE_STATUS,
                        CacheFlag.ROLE_TAGS,
                        CacheFlag.SCHEDULED_EVENTS
                )
                .setActivity(Activity.watching(
                        "the bot wakes up... " + Emoji.fromUnicode("\uD83D\uDCA4").getFormatted()
                ))
                .setShardsTotal(-1)
                .addEventListeners();

        shardManager = builder.build();
    }

    public static void main(String[] args) throws Exception {
        new Props().load("source/config/.properties");
        new Constant()
                .loadTranslations("source/translator/messages.json");

        new App();
    }
}
